name: container-apps-ai-mcp
services:
  mcp-host:
    build:
      context: ./mcp-host
    environment:
      - MCP_SERVER_HTTP_URL=http://mcp-server-http:3000/mcp
      - MCP_SERVER_SSE_URL=http://mcp-server-sse:3001/sse
      - DEBUG=
      # Uncomment the line below to enable debug logging
      - DEBUG=mcp:*
    env_file:
      - ./mcp-host/.env
    depends_on:
      - mcp-server-http
      - mcp-server-sse
  mcp-server-http:
    build:
      context: ./mcp-server-http
    ports:
      - '3000:3000'
    environment:
      # override the hostname provided in the .env file
      - POSTGRES_HOST=host.docker.internal
    env_file:
      - ./mcp-host/.env
    depends_on:
      - postgres
  mcp-server-sse:
    build:
      context: ./mcp-server-sse
    ports:
      - '3001:3001'
    environment:
      # override the hostname provided in the .env file
      - POSTGRES_HOST=host.docker.internal
    env_file:
      - ./mcp-host/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
